{"version":1,"defects":{"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::specific_exceptions":8,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::throws_for_unset_specific_exceptions":7},"times":{"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::specific_exceptions":0.015,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::throws_for_unset_specific_exceptions":0,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::does_not_throws_for_specific_exceptions":0,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::it_works_with_no_exceptions":0.001,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::failures_past_the_deadline_throw":0,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::too_many_consecutive_throw":0,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::too_many_total_throw":0,"Hammerstone\\Flaky\\Tests\\Unit\\BasicTest::reported_instead_of_thrown":0,"Hammerstone\\Flaky\\Tests\\Unit\\ArbiterTest::it_should_throw_because_of_total":0.015,"Hammerstone\\Flaky\\Tests\\Unit\\ArbiterTest::it_should_throw_because_of_consecutive":0,"Hammerstone\\Flaky\\Tests\\Unit\\ArbiterTest::it_should_throw_because_of_deadline":0.004,"Hammerstone\\Flaky\\Tests\\Unit\\ArbiterTest::an_allowed_failure_should_increment_both_and_carry_deadline":0,"Hammerstone\\Flaky\\Tests\\Unit\\ArbiterTest::a_success_should_update_cache":0,"Hammerstone\\Flaky\\Tests\\Unit\\CommandTest::varies_on_command":0.028,"Hammerstone\\Flaky\\Tests\\Unit\\CommandTest::scheduled_only":0.001,"Hammerstone\\Flaky\\Tests\\Unit\\CommandTest::scheduled_command_gets_modified":0.001,"Hammerstone\\Flaky\\Tests\\Unit\\RetryTest::it_will_retry":0,"Hammerstone\\Flaky\\Tests\\Unit\\RetryTest::it_retries_a_particular_exception_as_single":0,"Hammerstone\\Flaky\\Tests\\Unit\\RetryTest::it_retries_a_particular_exception_as_array":0,"Hammerstone\\Flaky\\Tests\\Unit\\SecondsTest::the_math_is_right":0}}